### ISSUE TITLE
Про уведомления должна решать сама модель, а не ее клиент

### ISSUE THREAD

**Issue by Znack** [kolodnikovm/blackjack#12]
а у тебя получается, что для корректной работы подписчиков тот, кто использует модель должен не только методы дергать правильные (дать карту тому, дать карту этому), так еще и помнить, что надо вызывать метод notify, это очень неявное API которому будет тяжело всегда следовать

**Comment by kolodnikovm** [comment]
Метод **notify()** должен вызываться внутри других методов модели и только? Если переносить его в один из методов модели, то он будет оповещать view при каждом изменении карт. В контроллере они обернуты логикой, что  только после полной раздачи каждому из игроков будет оповещение view. 
Могу я перенести из контроллера методы в модель? Или сделать в контроллере декоратор и навесить его на функции, требующие оповещения? В чем тогда суть контроллера?

**Comment by Znack** [comment]
Ты можешь контроллером подписаться на модель и вызывать нужные методы вью на сработанные события :) 
У тебя вью и модель друг про друга вообще не должны знать, собственно, это главная его цель

**Comment by kolodnikovm** [comment]
Структура проекта такова, что нажатая кнопка юзера вызывает определеннй метод Контроллера.
Эти определенные методы Контроллера ,в свою очередь, вызывают методы Модели в строгой последовательности, меняя параметры Модели нужным образом. Соответственно, после всех манипуляций со стороны Контроллера, Модель должна оповестить Вью, что данные изменились(текущий набор карт игрока) и отобразить их.

Если я подписываюсь  Контроллером на Модель то:

- Уже контроллер будет оповещать Вью, что отображать? А Модель через Контроллер передаст параметры для отображения. Получается, просто обернуть model.user.hand и model.user.score в метод Контроллера, чтобы он их возвращал? Из нужных методов Вью там только model_changed().
- Как мне работать с notify(), которые будут внутри методов Модели? Тогда любое изменение набора карт у игрока через методы Модели приведет к оповещению Вью, что значит дублирование и вывод информации после _каждой_ раздачи, а не после всех раздач.

В целом, можно поместить notify() оповещение в метод check_winner, что означает оповещение только перед начало новой раздачи карт, но не понимаю, как полностью избавиться от notify() внутри Контроллера без существенного изменения в системе слушателей.

**Comment by kolodnikovm** [comment]
На сколько я понял, Модель вообще самостоятельная структура, которая дает методы для работы с ней и никак, кроме них, данные модели не поменять, а Контроллер берет эти методы и оборачивает своей логикой. Но notify() мне нужно вызвать только при определенной комбинации методов изменения Модели, то есть в той логике, что реализует Контроллер.

**Comment by Znack** [comment]
А, так у тебя же вью слушает вообще модель напрямую, такого лучше избегать. У тебя все взаимодействие должно быть через контроллер. И контроллер может слушать модель, когда модель в себе что-то сама внезапно меняет (там у нее же своя бизнес логика может быть).

**Comment by Znack** [comment]
Так что notify вызовы точно стоит убрать из контроллера
