### ISSUE TITLE
Использовать приведение к типу вместо ручного форматирования

### ISSUE THREAD

**Issue by Znack** [kolodnikovm/blackjack#15]
У тебя форматирование вне Card делается так же, как ты уже реализовал приведение к строке, почему бы этим не воспользоваться? :)

**Comment by kolodnikovm** [comment]
Разве все форматирования  не вызывают __str__, который переопределен в Card? И по сути, этим и пользуюсь, когда сохраняю в БД user.hand или computer.hand. Или я чего-то не понимаю.

**Comment by Znack** [comment]
Поищи просто места по проекту, где ты приводишь к строкам объекты не через
str :)

вт, 26 дек. 2017 г. в 0:07, Maxim <notifications@github.com>:
