### ISSUE TITLE
В случае краша программы, новый запуск должен продолжать прошлую игру.

### ISSUE THREAD

**Issue by olgaklimenko** [kolodnikovm/blackjack#18]
Такое требование было описано в риззоме=) Сделали ctrl+c, запустили игру снова, и началась новая сессия, а не продолжилась старая. Еще такой вопрос, где-нибудь сохраняются сейчас прошлые сессии?

**Comment by kolodnikovm** [comment]
> новый запуск должен продолжать прошлую игру
 >  запустили игру снова, и началась новая сессия, а не продолжилась старая

Это не противоречивые требования? Или я просто не понимаю значения слов "игровая сессия" и "игра" – как я понял, в случае краша при повторном запуске нужно продолжить с места падения программы, как если бы игра продолжалась без перебоя.

**Comment by olgaklimenko** [comment]
Мы просто когда у себя развернули и попробовали, у нас с места падения программы не продолжилось ничего) Там мы даже нашли что тестовый можуль был подключен вместо того, который должен был)
