### ISSUE TITLE
В  try блоках должен быть самый минимум кода

### ISSUE THREAD

**Issue by Znack** [kolodnikovm/blackjack#4]
Вообще все, что не является прямо необходимым между try и except  должно быть вынесено :)

**Comment by kolodnikovm** [comment]
Там на try/except строится логика работы при крашах проги: 

- **Первый try** пытается считать буферный файл _data_, в котором лежит что-то(объект игры). Если ничего нет - значит выкинет EOF, предыдущая сессия закончилась нормально, начинаем по новой.
- **Второй try** запускает игру, если она восстановилась с предыдущей сессии и ловит ее ошибки.
- **Третий try** запускает игру, которая не была восстановлена из _data_ и ловит ее ошибки.

В общем своеобразный if-else, вроде и у Лутца прям говорилось, что try/except используют для таких целей.
