### ISSUE TITLE
Разделегировать отвествтенность по слоям

### ISSUE THREAD

**Issue by Znack** [kolodnikovm/blackjack#6]
Все что можно разнести по разным классам, должно быть разнесено. Каждый класс должен нести только одну четко обозначенную отвественность. Нельзя, чтобы в классе и бизнес-логика была, и управление csv файлом. В идеале вообще хранение данных инкапсулировать так, чтобы можно было потом легко подменить на какую-нибудь реальную базу безболезненно. Так что у работы с csv должен быть отдельный класс, который бы четко следовал созданному тобой контракту. Тогда потенциально туда можно любой другой класс подсунуть, который бы тоже следовал этому же контракту и все должно работать :) Главное, чтобы 
> If it walks like a duck and it quacks like a duck, then it must be a duck

**Comment by kolodnikovm** [comment]
Поправил :)
