### ISSUE TITLE
Сделать верхнеуровневый класс, который бы управлял всем приложением

### ISSUE THREAD

**Issue by Znack** [kolodnikovm/blackjack#7]
Кода, который бы не был разнесен по классам вообще должно быть минимум. В идеале должно быть всего две таких строчки: проверка, что  __main__ и создание инстанса :)

**Comment by kolodnikovm** [comment]
Заделал такой, но он пока в __init__ пакета app. На сколько я понял, там должно все создаваться,
чтобы при импорте уже были готовые объекты? На фласке видел пример, там обозначали функцию create_app, которая возвращала сам объект приложения.
