### ISSUE TITLE
Вьюху выделить в отдельный класс

### ISSUE THREAD

**Issue by Znack** [kolodnikovm/blackjack#8]
Лучше сразу выносить в отдельные слои все, что отвечает за представление и только это там и держать. В данном случае у тебя вьюха пока только консоль — так что весь вывод, кроме системных логов, должен быть оформлен в отдельном классе :)

**Comment by kolodnikovm** [comment]
Поправил :)

**Comment by Znack** [comment]
А ты в коммите в комментарии ишью укахывай через хеш и пиши Closed, будет закрываться сразу и тут ссылка будет на коммит :)
типа 
```
Closed #8
```
